### ISSUE TITLE
File Manager

### ISSUE THREAD

**Issue by thefrancisugorji** [mymocms/mymocms#30]
I having Server 500 Error on the Filemanager section
![Screenshot (22)](https://user-images.githubusercontent.com/53998128/121015720-364bf680-c793-11eb-93dc-43bd7dba6f52.png)

What can I do to solve this

**Comment by mymocms** [comment]
You can enable debug mode and capture your error message and send for me?

**Comment by thefrancisugorji** [comment]
> You can enable debug mode and capture your error message and send for me?

Done

The Error is in the image below

![Screenshot (23)](https://user-images.githubusercontent.com/53998128/121035923-402b2500-c7a6-11eb-8eab-38eeb97b40e5.png)

**Comment by mymocms** [comment]
You can reinstall an retry now

**Comment by thefrancisugorji** [comment]
Issue fixed and confirmed

Thanks for your help

**Comment by thefrancisugorji** [comment]
Hello another error

Error 500

ErrorException (E_NOTICE)
Undefined offset: 1

When I tried to delete an image from FileManager

Please reopen issue
